### ISSUE TITLE
Hello, can you share the cleaned dataset?

### ISSUE THREAD

**Issue by Algabeno** [tanvir-ishraq/TextThema-Multi-Classifier#1]
Hello, can you share the cleaned dataset?I want to try to do text style transfer.

**Comment by tanvir-ishraq** [comment]
@Algabeno 
Hello there!
`data/quote-nlp-dataset_cleaned.csv` should be the file you are looking for. I also added separate model training file `notebooks/textthema-multi-classifier-model.ipynb`, where you can load the file and get started right away.

**Comment by Algabeno** [comment]
I saw it, thank you very much! !
